// client.js — recipe interactivity: scale switching + cook mode
// Bundled with esbuild (IIFE) → site/recipe-app.js
import { toHTML, toGanttHTML } from "@gram-lang/renderer";

function initApp(root) {
  let data;
  try {
    data = JSON.parse(root.querySelector("script.recipe-data").textContent);
  } catch {
    return; // malformed embedded data — leave the static fallback alone
  }
  const renderEl = root.querySelector(".recipe-render");
  const ganttEl = root.querySelector(".gantt-render");
  const btns = [...root.querySelectorAll(".scale-btn")];
  let scale = "1";

  function setHTML(el, html) {
    // trusted: HTML generated by our own build pipeline, not user input
    const frag = new DOMParser().parseFromString(html, "text/html").body;
    el.replaceChildren(...frag.childNodes);
  }

  function render() {
    setHTML(renderEl, `<div class="gram-preview">${data[scale].html}</div>`);
    setHTML(ganttEl, data[scale].gantt);
    const slot = root.querySelector(".snippet-slot");
    if (slot && data[scale].snippet) setHTML(slot, data[scale].snippet);
    btns.forEach((b) =>
      b.classList.toggle("active", b.dataset.scale === scale)
    );
    exitCookMode();
  }

  btns.forEach((b) => b.addEventListener("click", () => {
    scale = b.dataset.scale;
    render();
  }));

  // --- Cook mode: step-through ---
  const cookBar = root.querySelector(".cook-bar");
  const cookLabel = root.querySelector(".cook-step-label");

  function steps() {
    return [...renderEl.querySelectorAll("ol.steps > li")];
  }
  function exitCookMode() {
    root.classList.remove("cooking");
    steps().forEach((s) => s.classList.remove("cook-active", "cook-done", "cook-pending"));
    cookBar?.removeAttribute("open");
  }
  function showStep(i) {
    const ss = steps();
    if (i >= ss.length) return exitCookMode();
    root.classList.add("cooking");
    if (cookBar) cookBar.setAttribute("open", "");
    ss.forEach((s, j) => {
      s.classList.toggle("cook-active", j === i);
      s.classList.toggle("cook-done", j < i);
      s.classList.toggle("cook-pending", j > i);
    });
    const secs = [...renderEl.querySelectorAll("section")];
    const active = ss[i].closest("section");
    secs.forEach((s) =>
      s.classList.toggle("cook-hidden-section", s !== active && !s.contains(ss[i]))
    );
    cookLabel.textContent = `Step ${i + 1}/${ss.length}`;
    ss[i].scrollIntoView({ behavior: "smooth", block: "center" });
  }

  root.querySelector(".cook-start")?.addEventListener("click", () => showStep(0));
  root.querySelector(".cook-next")?.addEventListener("click", () => {
    const i = steps().findIndex((s) => s.classList.contains("cook-active"));
    showStep(i + 1);
  });
  root.querySelector(".cook-exit")?.addEventListener("click", exitCookMode);

  render();
}

document.querySelectorAll(".recipe-app").forEach(initApp);

// --- Browse page: filterable recipe table ---
function fmtTime(min) {
  if (min == null) return "";
  const h = Math.floor(min / 60), m = Math.round(min % 60);
  return h ? `${h} h ${m ? m + " min" : ""}`.trim() : `${m} min`;
}

async function initBrowse() {
  const table = document.querySelector("#browse-table");
  if (!table) return;
  let recipes;
  try {
    recipes = await (await fetch("recipes-index.json")).json();
  } catch {
    table.textContent = "Failed to load recipe index.";
    return;
  }
  const tbody = table.querySelector("tbody");
  const search = document.querySelector("#browse-search");
  const catSel = document.querySelector("#browse-category");
  const count = document.querySelector("#browse-count");
  const cats = [...new Set(recipes.map((r) => r.category))].sort();
  for (const c of cats) catSel.add(new Option(c, c));
  let sortKey = "title", sortAsc = true;

  function rows() {
    const q = search.value.trim().toLowerCase();
    const cat = catSel.value;
    return recipes
      .filter(
        (r) =>
          (!cat || r.category === cat) &&
          (!q || `${r.title} ${r.category} ${r.source}`.toLowerCase().includes(q))
      )
      .sort((a, b) => {
        const va = a[sortKey], vb = b[sortKey];
        const c = typeof va === "number" ? va - vb : String(va).localeCompare(String(vb));
        return sortAsc ? c : -c;
      });
  }

  function render() {
    const rs = rows();
    tbody.replaceChildren(
      ...rs.map((r) => {
        const tr = document.createElement("tr");
        const td = (text) => {
          const c = document.createElement("td");
          c.textContent = text;
          return c;
        };
        const link = document.createElement("a");
        link.href = `cookbook/${r.slug}.html`;
        link.textContent = r.title;
        const titleTd = document.createElement("td");
        titleTd.append(link);
        tr.append(titleTd, td(r.category), td(fmtTime(r.time)), td(r.portions), td(r.source ?? ""));
        return tr;
      })
    );
    count.textContent = `${rs.length} / ${recipes.length} recipes`;
  }

  table.querySelectorAll("th[data-sort]").forEach((th) =>
    th.addEventListener("click", () => {
      const k = th.dataset.sort;
      sortAsc = k === sortKey ? !sortAsc : true;
      sortKey = k;
      table
        .querySelectorAll("th[data-sort]")
        .forEach((t) => t.classList.remove("sort-asc", "sort-desc"));
      th.classList.add(sortAsc ? "sort-asc" : "sort-desc");
      render();
    })
  );
  search.addEventListener("input", render);
  catSel.addEventListener("change", render);
  render();
}
initBrowse();
