// client.js — recipe interactivity: scale switching + cook mode
// Bundled with esbuild (IIFE) → site/recipe-app.js
import { toHTML, toGanttHTML } from "@gram-lang/renderer";
import {
  parseRecipeText,
  extractJsonLdRecipe,
  jsonLdToDraft,
  draftToGram,
  aiNeededTags,
} from "./import-parser.mjs";

function initApp(root) {
  let data;
  try {
    data = JSON.parse(root.querySelector("script.recipe-data").textContent);
  } catch {
    return; // malformed embedded data — leave the static fallback alone
  }
  const renderEl = root.querySelector(".recipe-render");
  const ganttEl = root.querySelector(".gantt-render");
  const btns = [...root.querySelectorAll(".scale-btn")];
  let scale = "1";

  function setHTML(el, html) {
    // trusted: HTML generated by our own build pipeline, not user input
    const frag = new DOMParser().parseFromString(html, "text/html").body;
    el.replaceChildren(...frag.childNodes);
  }

  function render() {
    setHTML(renderEl, `<div class="gram-preview">${data[scale].html}</div>`);
    setHTML(ganttEl, data[scale].gantt);
    const slot = root.querySelector(".snippet-slot");
    if (slot && data[scale].snippet) setHTML(slot, data[scale].snippet);
    btns.forEach((b) =>
      b.classList.toggle("active", b.dataset.scale === scale)
    );
    exitCookMode();
  }

  btns.forEach((b) => b.addEventListener("click", () => {
    scale = b.dataset.scale;
    render();
  }));

  // --- Cook mode: step-through ---
  const cookBar = root.querySelector(".cook-bar");
  const cookLabel = root.querySelector(".cook-step-label");

  function steps() {
    return [...renderEl.querySelectorAll("ol.steps > li")];
  }
  function exitCookMode() {
    root.classList.remove("cooking");
    steps().forEach((s) => s.classList.remove("cook-active", "cook-done", "cook-pending"));
    cookBar?.removeAttribute("open");
  }
  function showStep(i) {
    const ss = steps();
    if (i >= ss.length) return exitCookMode();
    root.classList.add("cooking");
    if (cookBar) cookBar.setAttribute("open", "");
    ss.forEach((s, j) => {
      s.classList.toggle("cook-active", j === i);
      s.classList.toggle("cook-done", j < i);
      s.classList.toggle("cook-pending", j > i);
    });
    const secs = [...renderEl.querySelectorAll("section")];
    const active = ss[i].closest("section");
    secs.forEach((s) =>
      s.classList.toggle("cook-hidden-section", s !== active && !s.contains(ss[i]))
    );
    cookLabel.textContent = `${document.documentElement.lang === "fr" ? "Étape" : "Step"} ${i + 1}/${ss.length}`;
    ss[i].scrollIntoView({ behavior: "smooth", block: "center" });
  }

  root.querySelector(".cook-start")?.addEventListener("click", () => showStep(0));
  root.querySelector(".cook-next")?.addEventListener("click", () => {
    const i = steps().findIndex((s) => s.classList.contains("cook-active"));
    showStep(i + 1);
  });
  root.querySelector(".cook-exit")?.addEventListener("click", exitCookMode);

  render();
}

document.querySelectorAll(".recipe-app").forEach(initApp);

// --- Browse page: filterable recipe table ---
function fmtTime(min) {
  if (min == null) return "";
  const h = Math.floor(min / 60), m = Math.round(min % 60);
  return h ? `${h} h ${m ? m + " min" : ""}`.trim() : `${m} min`;
}

async function initBrowse() {
  const table = document.querySelector("#browse-table");
  if (!table) return;
  let recipes;
  const fr = document.documentElement.lang === "fr";
  try {
    // fr pages live under /fr/ → index is one level up
    recipes = await (await fetch(fr ? "../recipes-index-fr.json" : "recipes-index.json")).json();
  } catch {
    table.textContent = fr
      ? "Échec du chargement de l’index des recettes."
      : "Failed to load recipe index.";
    return;
  }
  const tbody = table.querySelector("tbody");
  const search = document.querySelector("#browse-search");
  const catSel = document.querySelector("#browse-category");
  const count = document.querySelector("#browse-count");
  const cats = [...new Set(recipes.map((r) => r.category))].sort();
  for (const c of cats) catSel.add(new Option(c, c));
  let sortKey = "title", sortAsc = true;

  function rows() {
    const q = search.value.trim().toLowerCase();
    const cat = catSel.value;
    return recipes
      .filter(
        (r) =>
          (!cat || r.category === cat) &&
          (!q || `${r.title} ${r.category} ${r.source}`.toLowerCase().includes(q))
      )
      .sort((a, b) => {
        const va = a[sortKey], vb = b[sortKey];
        const c = typeof va === "number" ? va - vb : String(va).localeCompare(String(vb));
        return sortAsc ? c : -c;
      });
  }

  function render() {
    const rs = rows();
    tbody.replaceChildren(
      ...rs.map((r) => {
        const tr = document.createElement("tr");
        const td = (text) => {
          const c = document.createElement("td");
          c.textContent = text;
          return c;
        };
        const link = document.createElement("a");
        link.href = `cookbook/${r.slug}.html`;
        link.textContent = r.title;
        const titleTd = document.createElement("td");
        titleTd.append(link);
        tr.append(titleTd, td(r.category), td(fmtTime(r.time)), td(r.portions), td(r.source ?? ""));
        return tr;
      })
    );
    count.textContent = `${rs.length} / ${recipes.length} ${fr ? "recettes" : "recipes"}`;
  }

  table.querySelectorAll("th[data-sort]").forEach((th) =>
    th.addEventListener("click", () => {
      const k = th.dataset.sort;
      sortAsc = k === sortKey ? !sortAsc : true;
      sortKey = k;
      table
        .querySelectorAll("th[data-sort]")
        .forEach((t) => t.classList.remove("sort-asc", "sort-desc"));
      th.classList.add(sortAsc ? "sort-asc" : "sort-desc");
      render();
    })
  );
  search.addEventListener("input", render);
  catSel.addEventListener("change", render);
  render();
}
initBrowse();

// --- Import page: URL / raw text → .gram draft ---
async function fetchPage(url) {
  // direct first (CORS-permitting sites), then a markdown-reading proxy
  // ponytail: single proxy fallback; add more here if r.jina.ai rate-limits
  const attempts = [url, `https://r.jina.ai/${url}`];
  let lastErr;
  for (const u of attempts) {
    try {
      const res = await fetch(u);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.text();
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr ?? new Error("fetch failed");
}

function initImport() {
  const form = document.querySelector("#import-form");
  if (!form) return;
  const fr = document.documentElement.lang === "fr";
  const T = fr
    ? {
        needsReview: "⚠ À vérifier — traduction IA recommandée pour :",
        aiTip: "Essayez `npx gram import <url> --pick-model` pour une conversion assistée par IA.",
        parsed: (i, s) => `${i} ingrédients et ${s} étapes analysés.`,
        flagged: (n) => ` ${n} élément(s) marqué(s) à relire.`,
        clean: " Traduction statique qui semble complète.",
        enter: "Saisissez une URL de recette ou collez le texte de la recette.",
        urlPrefix: "L’URL doit commencer par http(s)://",
        fetching: "Récupération…",
        failed: (m) => `Échec de l’import : ${m}. Collez plutôt le texte de la recette.`,
        copied: "Copié dans le presse-papiers.",
      }
    : {
        needsReview: "⚠ Needs review — AI translation recommended for these:",
        aiTip: "Try `npx gram import <url> --pick-model` for AI-assisted conversion.",
        parsed: (i, s) => `Parsed ${i} ingredients and ${s} steps.`,
        flagged: (n) => ` ${n} item(s) flagged for review.`,
        clean: " Looks like a clean static translation.",
        enter: "Enter a recipe URL or paste the recipe text.",
        urlPrefix: "URL must start with http(s)://",
        fetching: "Fetching…",
        failed: (m) => `Import failed: ${m}. Paste the recipe text instead.`,
        copied: "Copied to clipboard.",
      };
  const urlIn = document.querySelector("#import-url");
  const textEl = document.querySelector("#import-text");
  const status = document.querySelector("#import-status");
  const out = document.querySelector("#import-output");
  const preview = out?.querySelector("#import-preview");
  let gramText = "";

  function show(msg, isError = false) {
    status.textContent = msg;
    status.classList.toggle("error", isError);
  }

  function emit(draft, meta) {
    gramText = draftToGram(draft, meta);
    const tags = aiNeededTags(draft);
    if (preview) preview.value = gramText;
    const tagBox = document.querySelector("#import-tags");
    tagBox.replaceChildren();
    if (tags.length) {
      const p = document.createElement("p");
      p.className = "import-tags-title";
      p.textContent = T.needsReview;
      const ul = document.createElement("ul");
      for (const t of tags) {
        const li = document.createElement("li");
        li.textContent = t;
        ul.append(li);
      }
      const tip = document.createElement("p");
      tip.textContent = T.aiTip;
      tagBox.append(p, ul, tip);
    }
    tagBox.hidden = !tags.length;
    out.hidden = false;
    show(
      `${T.parsed(draft.ingredients.length, draft.steps.length)}${tags.length ? T.flagged(tags.length) : T.clean}`,
      tags.length > 0 && (!draft.ingredients.length || !draft.steps.length),
    );
  }

  form.addEventListener("submit", async (e) => {
    e.preventDefault();
    out.hidden = true;
    const url = urlIn.value.trim();
    const raw = textEl.value.trim();
    try {
      if (raw && !url) {
        emit(parseRecipeText(raw), {});
        return;
      }
      if (!url) return show(T.enter, true);
      if (!/^https?:\/\//.test(url)) return show(T.urlPrefix, true);
      show(T.fetching);
      const body = await fetchPage(url);
      let recipe = null;
      try {
        recipe = extractJsonLdRecipe(body);
      } catch {
        /* plain-text body (e.g. r.jina.ai markdown) */
      }
      if (recipe) {
        const draft = jsonLdToDraft(recipe);
        if (!draft.title) draft.title = parseRecipeText("").title || url;
        emit(draft, { source: url, portions: String(recipe.recipeYield ?? "") });
      } else {
        emit(parseRecipeText(body, ""), { source: url });
      }
    } catch (err) {
      show(T.failed(err.message), true);
    }
  });

  // copy/download use the (possibly hand-edited) preview content
  const currentText = () => preview?.value || gramText;

  document.querySelector("#import-copy")?.addEventListener("click", async () => {
    await navigator.clipboard.writeText(currentText());
    show(T.copied);
  });
  document.querySelector("#import-download")?.addEventListener("click", () => {
    const gram = currentText();
    const title = gram.match(/^title: (.+)$/m)?.[1] ?? "recipe";
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([gram], { type: "text/plain" }));
    a.download = `${slug}.gram`;
    a.click();
    URL.revokeObjectURL(a.href);
  });
}
initImport();
